language: go
go:
- '1.12'

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libkrb5-dev

script:
- make dist

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - terraform-provider-freeipa_$TRAVIS_TAG-linux-amd64
  skip_cleanup: true
  on:
    tags: true
